use_frameworks!

platform :ios, '12.0'

target 'TranscriptionKit_Example' do
  pod 'TranscriptionKit', :path => '../'
  pod 'SwiftLint'
  
  pod 'AWSS3'
  pod 'AWSTranscribeStreaming'

  target 'TranscriptionKit_Tests' do
    inherit! :search_paths

    
  end
end
