use_frameworks!

platform :ios, '12.4'

plugin 'cocoapods-keys', {
  :project => 'TranscriptionKit',
  :keys => [
    'AwsTranscribeAccessKeyId',
    'AwsTranscribeSecretAccessKey'
  ]
}

target 'TranscriptionKit_Example' do
  pod 'TranscriptionKit', :path => '../'
  pod 'SwiftLint'

  target 'TranscriptionKit_Tests' do
    inherit! :search_paths

    
  end
end
